apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 'https://github.com/brano-hozza/reserver-webapi//deployments/kustomize/install' # ?ref=v1.0.1
- openapi-ui.service.yaml
- http-route.yaml

patches:
- path: patches/reserver-webapi.deployment.yaml