apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: reserver-ufe
spec:
  module-uri: http://reserver-ufe.wac-hospital/build/reserver-ufe.esm.js
                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: reserver-app 
      attributes:
        - name: api-base
          value: /reserver-api
      path: reserver     # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Room reserver     # názov mikro aplikácie
      details: App for room reservation at the hospital
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha1             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach