apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
 app.kubernetes.io/part-of: wac-hospital
 app.kubernetes.io/name: mandova-ambulance-wl

resources:
 - ../../../apps/mandova-ambulance-ufe
 - ../../../apps/mandova-ambulance-webapi


components:
 - ../../../components/version-release