apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ../../../infrastructure/ufe-controller
- ../../../infrastructure/fluxcd

patches:
- path: patches/ufe-controller.service.yaml