apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserver-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /reserver-openapi
            - name: BASE_URL
              value: /reserver-openapi-ui